Updated more scripts

diff --git a/scripts/manila b/scripts/manila
--- a/scripts/manila
+++ b/scripts/manila
@@ -3,31 +3,22 @@
 # Script for mounting the BU reports drive over the network
 
 # Maintainer:       Ben Buchanan
-# Version:          1.0.2
-# Last Modified:    03-Jun-2026
+# Version:          1.0.3
+# Last Modified:    10-Jun-2026
 
-if [ "$EUID" -ne 0 ]
-then
-    ENV_FILE="$HOME/.env.sh"
-else
-    ENV_FILE="/.env.sh"
-fi
+die() {
+    dunstify 'ERROR' "$1"
+    exit 1
+}
 
-if [ -f "$ENV_FILE" ]
-then
-    # shellcheck disable=SC1090
-    source "$ENV_FILE"
-else
-    dunstify 'Error when mounting' "Could not locate env file at '$ENV_FILE'"
-    exit
-fi
+ENV_FILE="$HOME/.env.sh"
+(( EUID == 0 )) && ENV_FILE="/.env.sh"
+
+[[ -f "$ENV_FILE" ]] || die "Could not locate env file at '$ENV_FILE'"
+# shellcheck disable=SC1090
+source "$ENV_FILE"
 
 REPORTS_MOUNT_DIR=/mnt/reports/
+[[ -d $REPORTS_MOUNT_DIR ]] || die "Mountpoint '$REPORTS_MOUNT_DIR' does not exist"
 
-if [ -d $REPORTS_MOUNT_DIR ]
-then
-    mount "$BU_REPORTS_PATH" "$REPORTS_MOUNT_DIR" -o user="$BU_REPORTS_USER"
-else
-    dunstify 'Error when mounting' "'$REPORTS_MOUNT_DIR' does not exist"
-    exit
-fi
+mount "$BU_REPORTS_PATH" "$REPORTS_MOUNT_DIR" -o user="$BU_REPORTS_USER"
diff --git a/scripts/mosaic b/scripts/mosaic
--- a/scripts/mosaic
+++ b/scripts/mosaic
@@ -3,13 +3,13 @@
 # Select and apply a screen layout
 
 # Maintainer:       Ben Buchanan
-# Version:          2.1.0
-# Last Modified:    09-Jun-2026
+# Version:          2.1.1
+# Last Modified:    10-Jun-2026
 
 XRESOURCES=$HOME/.Xresources
 
 FONT="Terminus-10"
-BACKGROUND=$(awk '/color0:/ {print $2}' "$XRESOURCES")
+BACKGROUND=$(awk '/background:/ {print $2}' "$XRESOURCES" | head -n 1)
 FOREGROUND=$(awk '/color8:/ {print $2}' "$XRESOURCES")
 
 DMENU_SETTINGS=(-nb "$BACKGROUND" -nf "$FOREGROUND" \
@@ -24,66 +24,64 @@ STATUSBAR=polybar
 
 LAYOUT_DIR="$HOME/.config/mosaic/layouts"
 
-getLayouts() {
-    LAYOUTS="$(ls -1 "$LAYOUT_DIR")"
-    if [ -z "$LAYOUTS" ]; then
-        dunstify "ERROR" "Could not read layouts from $LAYOUT_DIR!"
-        exit
-    fi
-}
-
-getChoice() {
-    CHOICE="$(echo -e "\n$LAYOUTS" | dmenu -l 30 "${DMENU_SETTINGS[@]}" -i -p 'Choose a Layout:')"
-    if [ -z "$CHOICE" ]; then
-        dunstify "ERROR" "User did not pick a valid layout!"
-        exit
-    fi
-}
-
-getLayouts
-getChoice
-
 DISPLAYS="$(xrandr | grep ' connected')"
 
-declare -a XRANDR_OPTS
+die() {
+    dunstify 'ERROR' "$1"
+    exit 1
+}
 
-while read -r line; do
-    [[ $line =~ ^output\ +(.*)$ ]] && {
-        output="${BASH_REMATCH[1]}"
-        exists="$(echo "$DISPLAYS" | grep "$output")"
+get_layouts() {
+    LAYOUTS="$(ls -1 "$LAYOUT_DIR")"
+    [[ -z "$LAYOUTS" ]] && die "Could not read layouts from '$LAYOUT_DIR'"
+}
 
-        [[ -z $exists ]] && {
-            dunstify "ERROR" "Could not detect display '$output'"
-            exit
+get_choice() {
+    CHOICE="$(echo -e "\n$LAYOUTS" | dmenu -l 30 "${DMENU_SETTINGS[@]}" -i -p 'Choose a Layout:')"
+    [[ -z "$CHOICE" ]] && exit 0
+}
+
+parse_xrandr_opts() {
+    declare -aG XRANDR_OPTS
+
+    local line output exists
+    while read -r line; do
+        [[ $line =~ ^output\ +(.*)$ ]] && {
+            output="${BASH_REMATCH[1]}"
+            exists="$(echo "$DISPLAYS" | grep "$output")"
+
+            [[ -z $exists ]] && die "Could not detect display '$output'"
+
+            XRANDR_OPTS+=("--output")
+            XRANDR_OPTS+=("${BASH_REMATCH[1]}")
         }
 
-        XRANDR_OPTS+=("--output")
-        XRANDR_OPTS+=("${BASH_REMATCH[1]}")
-    }
+        [[ $line =~ ^primary$ ]] && XRANDR_OPTS+=("--primary")
+        [[ $line =~ ^mode\ +(.+x.+)$ ]] && {
+            XRANDR_OPTS+=("--mode")
+            XRANDR_OPTS+=("${BASH_REMATCH[1]}")
+        }
+        [[ $line =~ ^pos\ +(.+x.+)$ ]] && {
+            XRANDR_OPTS+=("--pos")
+            XRANDR_OPTS+=("${BASH_REMATCH[1]}")
+        }
+        [[ $line =~ ^rotate\ +(.+)$ ]] && {
+            XRANDR_OPTS+=("--rotate")
+            XRANDR_OPTS+=("${BASH_REMATCH[1]}")
+        }
+    done < "$LAYOUT_DIR/$CHOICE"
+}
 
-    [[ $line =~ ^primary$ ]] && {
-        XRANDR_OPTS+=("--primary")
-    }
-    [[ $line =~ ^mode\ +(.+x.+)$ ]] && {
-        XRANDR_OPTS+=("--mode")
-        XRANDR_OPTS+=("${BASH_REMATCH[1]}")
-    }
-    [[ $line =~ ^pos\ +(.+x.+)$ ]] && {
-        XRANDR_OPTS+=("--pos")
-        XRANDR_OPTS+=("${BASH_REMATCH[1]}")
-    }
-    [[ $line =~ ^rotate\ +(.+)$ ]] && {
-        XRANDR_OPTS+=("--rotate")
-        XRANDR_OPTS+=("${BASH_REMATCH[1]}")
-    }
-done < "$LAYOUT_DIR/$CHOICE"
+get_layouts
+get_choice
+parse_xrandr_opts
 
 xrandr "${XRANDR_OPTS[@]}"
 
 # Restart polybar on new layout
 pkill $STATUSBAR
 TOGGLE_STATE=$(cat "$GAPS_TOGGLE")
-[ "$TOGGLE_STATE" == "On" ] && marquee gaps
-[ "$TOGGLE_STATE" == "Off" ] && marquee no-gaps
+[[ "$TOGGLE_STATE" == "On" ]] && marquee gaps
+[[ "$TOGGLE_STATE" == "Off" ]] && marquee no-gaps
 
 feh --bg-fill "$CURRENT_WALLPAPER"
