Updated slip, added better configuration

diff --git a/scripts/slip b/scripts/slip
--- a/scripts/slip
+++ b/scripts/slip
@@ -4,16 +4,17 @@
 # A script for presenting slides in the terminal
 
 # Maintainer:       Ben Buchanan
-# Version:          0.4.0
-# Last Modified:    11-Mar-2024
+# Version:          0.5.0
+# Last Modified:    12-Mar-2024
 
 ## Present slides in the terminal
 ##
 ## Usage: $0 [OPTIONS] <FILE>
 ##
 ## Options:
-##   -h, --help     Show this usage output
-##   -v, --version  Show the version of the script
+##   -h, --help                     Show this usage output
+##   -v, --version                  Show the version of the script
+##   -c=<FILE>, --config=<FILE>     Specify a local config file to use
 
 SCRIPT="${BASH_SOURCE[0]##*/}"
 
@@ -40,8 +41,8 @@ print_version () {
 
 main () {
     process_args "$@"
-    process_config
-    process_input_file "$1"
+    process_config "$local_config_path"
+    process_input_file "$presentation_file_path"
 
     current_slide=0
 
@@ -68,8 +69,6 @@ process_args () {
     positional_args=()
 
     for arg in "$@"; {
-        # TODO: Arguments for turning off rendering for certain elements
-        # TODO: Argument for local config file
         case $arg in
             -h|--help)
                 print_usage
@@ -78,6 +77,9 @@ process_args () {
             -v|--version)
                 print_version
                 exit 0
+                ;;
+            -c=*|--config=*)
+                local_config_path="${arg##*=}"
                 ;;
             -*)
                 arg="${arg##*-}"
@@ -88,7 +90,6 @@ process_args () {
                 ;;
             *)
                 positional_args+=("$arg") # save positional args
-                shift # past argument
                 ;;
         esac
     }
@@ -96,10 +97,27 @@ process_args () {
     # Restore positional args
     set -- "${positional_args[@]}"
 
-    # TODO: More robust file validation
-    # TODO: If no file is provided, print usage
-    [[ -f "$1" ]] || {
-        printf 'Please provide a valid file.\n'
+    # If no file is provided, print usage
+    [[ $# -gt 0 ]] || {
+        print_usage
+        exit 0
+    }
+
+    # Ensure provided local config file exists
+    [[ -n "$local_config_path" ]] && {
+        [[ -f "$local_config_path" ]] || {
+            printf '%s: bad file -- %s\n' "$SCRIPT" "'$local_config_path'"
+            printf 'Provided local config file must be a regular file.\n'
+            exit 1
+        }
+    }
+
+    # Ensure provided file is readable by slip
+    # NOTE: This does not guarantee that it is a well-formatted Markdown file
+    presentation_file_path="$1"
+    [[ -f "$presentation_file_path" ]] || {
+        printf '%s: bad file -- %s\n' "$SCRIPT" "'$presentation_file_path'"
+        printf 'Provided presentation file must be a regular file.\n'
         exit 1
     }
 }
@@ -143,22 +161,52 @@ process_config () {
         [CODE_BLOCK_FUNC_STYLE]=''
         [BLOCKQUOTE_STYLE]='HIGHLIGHT'
         [TABLE_STYLE]=''
+
+        # RENDERING
+        [RENDER_BORDER_BARS]='TRUE'
+        [RENDER_TITLE]='TRUE'
+        [RENDER_AUTHOR]='TRUE'
+        [RENDER_SLIDE_NUMBERS]='TRUE'
+
+        # OTHER
+        [BORDER_BAR_CHARACTER]='='
     )
 
     [[ -f "$XDG_CONFIG_HOME/slip/sliprc" ]] && {
         while read -r line; do
-            [[ $line =~ ^\ *([0-9a-zA-Z_]*)\ *=\ *([0-9a-zA-Z_,\ ]*)\ *$ ]] && {
+            [[ $line =~ ^\ *([a-zA-Z_]*)\ *=\ *(.*)\ *$ ]] && {
                 key="${BASH_REMATCH[1]^^}"
                 val="${BASH_REMATCH[2]^^}"
 
                 # Validate color numbers
-                [[ $key == *COLOR ]] && validate_color_num "$val"
+                [[ $key == *COLOR ]] && validate_color_num "$val" "$key"
                 # Validate style strings
-                [[ $key == *STYLE ]] && validate_styles "$val"
+                [[ $key == *STYLE ]] && validate_styles "$val" "$key"
+                # Validate render bools
+                [[ $key == RENDER* ]] && validate_bool "$val" "$key"
 
                 config[$key]=$val
             }
         done < "$XDG_CONFIG_HOME/slip/sliprc"
+    }
+
+    # If we got a local config file, read from that last
+    [[ -f "$1" ]] && {
+        while read -r line; do
+            [[ $line =~ ^\ *([a-zA-Z_]*)\ *=\ *(.*)\ *$ ]] && {
+                key="${BASH_REMATCH[1]^^}"
+                val="${BASH_REMATCH[2]^^}"
+
+                # Validate color numbers
+                [[ $key == *COLOR ]] && validate_color_num "$val" "$key"
+                # Validate style strings
+                [[ $key == *STYLE ]] && validate_styles "$val" "$key"
+                # Validate render bools
+                [[ $key == RENDER* ]] && validate_bool "$val" "$key"
+
+                config[$key]=$val
+            }
+        done < "$1"
     }
 
     # Convert values into actual printable styles
@@ -181,7 +229,9 @@ process_config () {
 validate_color_num () {
     # We only allow the xterm colors 0-8
     [[ $1 =~ ^[0-8]$ ]] || {
-        printf '%s is not a valid color number.\n' "'$1'"
+        printf '%s: error in config file\n' "$SCRIPT"
+        printf '%s is not a valid value for option %s.\n' "'$1'" "'$2'"
+        printf 'Value must be an integer between 0-8 (inclusive).\n'
         exit 1
     }
 }
@@ -197,10 +247,22 @@ validate_styles () {
             HIGHLIGHT)
                 ;;
             *)
-                printf '%s is not a valid style.\n' "'$style'"
+                printf '%s: error in config file\n' "$SCRIPT"
+                printf '%s is not a valid value for option %s.\n' "'$style'" "'$2'"
+                printf 'Value must be one of: [BOLD, UNDERLINE, ITALIC, HIGHLIGHT].\n'
                 exit 1
                 ;;
         esac
+    }
+}
+
+validate_bool () {
+    # We only allow 'true' or 'false'
+    [[ $1 =~ ^(TRUE|FALSE)$ ]] || {
+        printf '%s: error in config file\n' "$SCRIPT"
+        printf '%s is not a valid value for option %s.\n' "'$1'" "'$2'"
+        printf "Value must be either 'TRUE' or 'FALSE'.\n"
+        exit 1
     }
 }
 
@@ -396,6 +458,8 @@ slide_header () {
     move 0 0
     border_bar
 
+    [[ ${config['RENDER_TITLE']} == TRUE ]] || return
+
     subtitle="${subtitles[$current_slide]}"
     title="${metadata['TITLE']}${subtitle:+" > $subtitle"}"
     set_modifiers "${config['TITLE_COLOR']}"
@@ -405,10 +469,12 @@ slide_header () {
 }
 
 border_bar () {
+    [[ ${config['RENDER_BORDER_BARS']} == TRUE ]] || return
+
     printf -v hline "%${COLUMNS}s"
     set_modifiers "${config['BORDER_COLOR']}"
     set_modifiers "${config['BORDER_STYLE']}"
-    printf '%s' "${hline// /=}"
+    printf '%s' "${hline// /${config['BORDER_BAR_CHARACTER']}}"
     reset_modifiers
 }
 
@@ -429,6 +495,8 @@ slide_footer () {
 }
 
 author_name () {
+    [[ ${config['RENDER_AUTHOR']} == TRUE ]] || return
+
     author="${metadata['AUTHOR']}"
 
     move "$((LINES - 2))" 3
@@ -439,6 +507,8 @@ author_name () {
 }
 
 slide_number () {
+    [[ ${config['RENDER_SLIDE_NUMBERS']} == TRUE ]] || return
+
     move "$((LINES - 2))" "$((COLUMNS - 4))"
     set_modifiers "${config['SLIDE_NUMBER_COLOR']}"
     set_modifiers "${config['SLIDE_NUMBER_STYLE']}"
