Finished updating scripts

diff --git a/scripts/soundspool b/scripts/soundspool
--- a/scripts/soundspool
+++ b/scripts/soundspool
@@ -3,24 +3,20 @@
 # A script to turn squeezelite on and off
 
 # Maintainer:       Ben Buchanan
-# Version:          1.0.2
-# Last Modified:    03-Jun-2026
+# Version:          1.0.3
+# Last Modified:    11-Jun-2026
 
-if [ "$EUID" -ne 0 ]
-then
-    ENV_FILE="$HOME/.env.sh"
-else
-    ENV_FILE="/.env.sh"
-fi
+die() {
+    dunstify 'ERROR' "$1"
+    exit 1
+}
 
-if [ -f "$ENV_FILE" ]
-then
-    # shellcheck disable=SC1090
-    source "$ENV_FILE"
-else
-    dunstify 'Error' "Could not locate env file at '$ENV_FILE'"
-    exit
-fi
+ENV_FILE="$HOME/.env.sh"
+(( EUID == 0 )) && ENV_FILE="/.env.sh"
+
+[[ -f "$ENV_FILE" ]] || die "Could not locate env file at '$ENV_FILE'"
+# shellcheck disable=SC1090
+source "$ENV_FILE"
 
 if ! pkill squeezelite
 then
